/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BasicAside: typeof import('./src/layouts/components/basic/BasicAside.vue')['default']
    BasicHeader: typeof import('./src/layouts/components/basic/BasicHeader.vue')['default']
    BasicLayout: typeof import('./src/layouts/components/basic/BasicLayout.vue')['default']
    BasicMain: typeof import('./src/layouts/components/basic/BasicMain.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
